// Service containing operations for Announcements
// Placed in a separate file to keep the project modular and ready for backend integration

/**
 * Sends announcement data to the backend API.
 * Currently prints the payload in the console for learning purposes.
 * 
 * @param {Object} data - The announcement data
 * @param {string} data.title - The title of the announcement
 * @param {string} data.content - The HTML content generated by the rich text editor
 * @returns {Promise<Object>} A promise resolving to a mock response
 */
async function saveAnnouncement(data) {
    // For learning purposes only, we log the payload to the browser console.
    // In production/future integration, this would be:
    // const response = await api.post("/admin/announcements", data);
    // return response.data;
    
    console.log("Announcement Service - Payload Received:", data);
    
    // Return a mock successful response to mimic an API response
    return {
        success: true,
        message: "Announcement saved successfully (Simulated Backend Response)",
        data
    };
}

export default {
    saveAnnouncement
};
